services:
  fashionstore.webapp:
    image: ${DOCKER_REGISTRY-}fashionstorewebapp
    build:
      context: .
      dockerfile: src/FashionStore.WebApp/Dockerfile
    depends_on: 
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y
    volumes:
      - sql_data:/var/opt/mssql
volumes:
  sql_data: